version : latest

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: default_user
      POSTGRES_PASSWORD: bananenauto
      POSTGRES_DB: file-transfer
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: